server:
  port: 8080
  servlet:
    context-path: /identity
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/identity_service"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: "HZuyxxBcO2Kg1/bbyXGK535o4F7ZMfYm6uLuhTQmHMulsPPQFeb4O91F1fBy1PDe+DWm9CX3q23f0La6vwDj/DhiP0VgNELfPo011e/m5Yk="
  expiration: 3600000  #  in milliseconds (1 hour)

